# wrangler.toml

# General Worker settings
name = "example"
main = ".open-next/worker.js"
compatibility_date = "2025-06-13"

# Compatibility Flags
compatibility_flags = [
	"nodejs_compat"
]

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "my-local-cache-bucket"
preview_bucket_name = "my-local-cache-bucket-preview"

[assets] # Note: The closing bracket was missing in your original input, I've corrected it.
directory = ".open-next/assets"
binding = "ASSETS" # This is the variable name that will be available in your Worker to access assets